version: '3'
services:

  erxsyslog: # Docker container name
    build:
      context: /home/home/erx # Folder name where you have cloned files
      dockerfile: dockerfile # Docker build file, no change needed, must be under above listed folder
    image: erxsyslog
    container_name: erxsyslog # Docker container name
    network_mode: "host"
    volumes:
      - /home/home/erx:/config # Folder name where you have config file
      - /etc/localtime:/etc/localtime:ro # Time sync to host machine
    restart: unless-stopped  # Restart policy
